[phases.setup]
nixPkgs = ["nodejs_24", "openssl"]

[phases.build]
cmds = ["npm ci", "npx prisma generate", "npm run build", "cp -r public .next/standalone/public", "cp -r .next/static .next/standalone/.next/static"]

[start]
cmd = "sh start.sh"
